---
# install rbenv
# this playbook should be run with {{ rbenv_user }} instead of root

- name: clone rbenv repo
  git: repo=https://github.com/sstephenson/rbenv.git 
       dest=/home/{{ rbenv_user }}/.rbenv

- name: Add rbenv to the PATH
  lineinfile:
    dest=/home/{{ rbenv_user }}/.bashrc
    line='export PATH="$HOME/.rbenv/bin:$PATH"'
    state=present

- name: enable rbenv
  lineinfile:
    dest=/home/{{ rbenv_user }}/.bashrc
    line='eval "$(rbenv init -)"'
    state=present

- name: mkdir ~/.rbenv/plugins
  file: path=/home/{{ rbenv_user }}/.rbenv/plugins state=directory
        owner={{ rbenv_user }} group={{ rbenv_user }} mode=0755

# install ruby build plugin
- name: clone ruby build repo
  git: repo=git://github.com/sstephenson/ruby-build.git 
       dest=/home/{{ rbenv_user }}/.rbenv/plugins/ruby-build
  when: rbenv_ruby_build == True

# install rbenv-gem-rehash
# Never run rbenv rehash again
- name: install rbenv-gem-rehash
  git: repo=https://github.com/sstephenson/rbenv-gem-rehash.git
       dest=/home/{{ rbenv_user }}/.rbenv/plugins/rbenv-gem-rehash
  when: rbenv_gem_rehash == True

# install rbenv-binstubs plugin; uncomment to install
# it makes rbenv transparently aware of project-specific binstubs created by bundler
- name: install rbenv-binstubs plugin
  git: repo=git@github.com:ianheggie/rbenv-binstubs.git
       dest=/home/{{ rbenv_user }}/.rbenv/plugins/rbenv-binstubs
  when: rbenv_binstubs == True

- name: install rbenv-vars
  git: repo=https://github.com/sstephenson/rbenv-vars.git
       dest=/home/{{ rbenv_user }}/.rbenv/plugins/rbenv-vars
  when: rbenv_vars == True

- name: chown .rbenv dir
  command: chown -R {{ rbenv_user }}.{{ rbenv_user }} /home/{{ rbenv_user }}/.rbenv
